services:
  # TODO: this must be removed when either zig linter is fixed or we get rid of snappy package
  ochi-tsan:
    build:
      context: ..
      dockerfile: Dockerfile.debug
      args:
        OPTIMIZE: Debug
        TRACY: true
    environment:
      TSAN_OPTIONS: "external_symbolizer_path=/usr/bin/llvm-symbolizer,symbolize=1,halt_on_error=1,verbosity=1"
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    command: ["/usr/local/bin/ochi"]
    profiles: ["debug"]
    ports:
      - "9014:9014"
      - "8086:8086"

  ochi:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        OPTIMIZE: ReleaseSafe
        TRACY: false
        PPROF: true
    command: ["/usr/local/bin/ochi"]
    cgroup_parent: ochi.slice
    profiles: ["profile"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    ports:
      - "9014:9014"
      - "8086:8086"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    # cAdvisor needs host-level visibility to report metrics for all containers
    privileged: true
    pid: host
    ports:
      - "8080:8080"
    volumes:
      # host root filesystem context for filesystem/path resolution
      - /:/rootfs:ro
      # runtime sockets for container runtime discovery and metadata
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # host kernel and cgroup stats source: cpu, memory, blkio (block device io), network
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # docker storage metadata for layer/filesystem usage insights
      - /var/lib/docker:/var/lib/docker:ro
      # host containerd socket used by docker
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    command:
      - --docker_only=true
      - --docker=unix:///var/run/docker.sock
      - --containerd=/run/containerd/containerd.sock
      - --containerd-namespace=moby
      - --housekeeping_interval=15s
      - --store_container_labels=true
      - --disable_root_cgroup_stats=true
      - --disable_metrics=advtcp,cpuset,cpu_topology,disk,diskIO,hugetlb,network,perf_event,percpu,pressure,referenced_memory,resctrl,sched,tcp,udp
    profiles: ["profile"]

  pyroscope:
    image: 'grafana/pyroscope:latest'
    ports:
      - '4040:4040'
    profiles: ["profile"]

  alloy:
    image: 'grafana/alloy:latest'
    privileged: true
    pid: host
    volumes:
      - ./alloy.config:/etc/alloy/config.alloy
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
    command: run /etc/alloy/config.alloy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pyroscope
    profiles: ["profile"]

  prometheus:
    image: prom/prometheus:v3.4.2
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      # enables reload API
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    profiles: ["profile"]

  grafana:
    image: grafana/grafana:11.1.4
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_SIGNOUT_MENU: true
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    profiles: ["profile"]
